---
- import_tasks: apt-pkg.yml
  when: (ansible_facts['distribution'] == "Ubuntu")

- import_tasks: yum-pkg.yml
  when: (ansible_facts['distribution'] == "CentOS")

- import_tasks: zsh.yml
  vars:
    user: "{{ common_username }}"
  when: common_user

- import_tasks: zsh.yml
  vars:
    user: root
    home_dir: "/"
