---
- name: install epel release on centos
  ansible.builtin.yum:
    name: epel-release

- name: install util-linux-use on centos
  ansible.builtin.yum:
    name: yum-utils
    state: "present"
    update_cache: true
  changed_when: false

- name: install system packages and utils on centos
  ansible.builtin.yum:
    name: ["{{ item }}"]
    state: "present"
    update_cache: true
  with_items: "{{ yum_pkg_install }}"
  changed_when: false
